language: node_js
node_js:
  - "16"
  
language: java

jdk:
  - semeru17


before_install:
 

  # Install Sonar Scanner
  - curl -sSLo sonar-scanner.zip https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-4.7.0.2747-linux.zip
  - unzip sonar-scanner.zip
  - export PATH=$PATH:$PWD/sonar-scanner-4.7.0.2747-linux/bin

install:
  - npm install

script:
  - npm test

after_success:
  - |
    sonar-scanner \
      -Dsonar.projectKey=travis-sonarqube \
      -Dsonar.sources=. \
      -Dsonar.host.url=https://sonar.eha.ng/ \
      -Dsonar.login=$TRAVIS_SONARQUBE \
      -X
