language: generic

services:
  - docker

before_script:
  # Install Trivy
  - wget https://github.com/aquasecurity/trivy/releases/latest/download/trivy_0.56.2_Linux-64bit.deb
  - sudo dpkg -i trivy_0.56.2_Linux-64bit.deb

script:
  # Build Docker image
  - docker build -t trivy-travis:latest .
  # Scan Docker image with Trivy and save the report in txt format
  - trivy image --exit-code 1 --severity HIGH,CRITICAL --format table -o trivy-report.txt trivy-travis:latest || true

after_script:
  # Configure git
  - git config --global user.email "kumar.gj@axxonet.net"
  - git config --global user.name "kumar-axxonet"

  # Checkout the branch for reports, create if it doesn't exist
  - git checkout -b trivy-travis-reports || git checkout trivy-travis-reports

  # Add and commit the Trivy report
  - git add trivy-report.txt
  - git commit -m "Add Trivy scan report on $(date +'%Y-%m-%d')"
  
  # Push to the repository using the GITHUB_TOKEN
  - git push https://$GITHUB_TOKEN@github.com/eHealthAfrica/trivy-travis.git trivy-travis-reports


  
#language: generic: Specifies a generic environment , for Docker
#services: docker:  enables Docker within the Travis CI environment.
#before_script: Installs Trivy on the Travis CI environment

