language: generic

services:
  - docker

before_script:
  # Install Trivy
  - wget https://github.com/aquasecurity/trivy/releases/latest/download/trivy_0.56.2_Linux-64bit.deb
  - sudo dpkg -i trivy_0.56.2_Linux-64bit.deb
  - echo "DefectDojo URL: ${DEFECTDOJO_URL}"

script:
  # Build Docker image
  - docker build -t trivy-travis:latest .
  # Scan Docker image with Trivy and save the report in txt format
  - trivy image --exit-code 1 --severity HIGH,CRITICAL --format json -o trivy-report.json trivy-travis:latest || true

after_script:
  - echo "Uploading report to DefectDojo..."
  - echo "DefectDojo URL: ${DEFECTDOJO_URL}"
  - |
    curl -X POST \
      "${DEFECTDOJO_URL}" \
      -H 'accept: application/json' \
      -H 'Authorization: DEFECTDOJO_API_TOKEN' \
      -H 'Content-Type: multipart/form-data' \
      -F 'test=33' \
      -F 'file=@$trivy-report.json;type=application/json' \
      -F 'scan_type=Trivy Scan' \
      -F 'tags=sample' \
      --max-time 300


  
#language: generic: Specifies a generic environment , for Docker
#services: docker:  enables Docker within the Travis CI environment.
#before_script: Installs Trivy on the Travis CI environment
