language: java

jdk:
  - semeru17  # Use JDK 17 (Semeru version)

node_js:
  - node 

before_install:
  - node -v  # Verify Node.js version
  - echo "Node.js version is $(node -v)"   # Print Node.js version to the log for verification
  
  # Install Sonar Scanner
  - curl -L -sSLo sonar-scanner.zip https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-6.2.0.4584-linux-x64.zip
  - unzip sonar-scanner.zip
  - export PATH=$PATH:$PWD/sonar-scanner-6.2.0.4584-linux-x64/bin

env:
  - SONAR_NODEJS_EXECUTABLE=$(which node)  # Set the Node.js executable path for SonarQube

install:
  - npm install  # Install dependencies

script:
  - npm test  # Run your tests

after_success:
  - |
    sonar-scanner \
      -Dsonar.projectKey=travis-sonarqube \
      -Dsonar.sources=. \
      -Dsonar.host.url=https://sonar.eha.ng/ \
      -Dsonar.login=$TRAVIS_SONARQUBE \
      -Dsonar.nodejs.executable=$SONAR_NODEJS_EXECUTABLE  # Use the SONAR_NODEJS_EXECUTABLE environment variable
      -X  # Run with debug output
