language: minimal  # Use minimal to avoid Travis's default Node.js setup

jdk:
  - semeru17  

before_install:
  # Update and install prerequisites
  - sudo apt-get update
  - sudo apt-get install -y software-properties-common
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test  
  - sudo apt-get update
  - sudo apt-get install -y libstdc++-8-dev libc6-dev
  - wget http://ftp.gnu.org/gnu/libc/glibc-2.28.tar.gz
  - tar -xvzf glibc-2.28.tar.gz
  - cd glibc-2.28
  - mkdir build
  - cd build
  - ../configure --prefix=/opt/glibc-2.28
  - - make -s -j$(nproc) > build.log 2>&1
  - tail -n 100 build.log
  - sudo make install
  - export LD_LIBRARY_PATH=/opt/glibc-2.28/lib:$LD_LIBRARY_PATH

  # Install Node.js manually
  - curl -fsSL https://deb.nodesource.com/setup_22.x | sudo -E bash -
  - sudo apt-get install -y nodejs
  - node -v  # Verify Node.js version
  - npm -v   # Verify npm version
  
  # Install Sonar Scanner
  - curl -L -sSLo sonar-scanner.zip https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-6.2.0.4584-linux-x64.zip
  - unzip sonar-scanner.zip
  - export PATH=$PATH:$PWD/sonar-scanner-6.2.0.4584-linux-x64/bin

env:
  - SONAR_NODEJS_EXECUTABLE=$(which node)

install:
  - npm install  # Install dependencies

script:
  - npm test  # Run your tests

after_success:
  - |
    sonar-scanner \
      -Dsonar.projectKey=travis-sonarqube \
      -Dsonar.sources=. \
      -Dsonar.host.url=https://sonar.eha.ng/ \
      -Dsonar.login=$TRAVIS_SONARQUBE \
      -Dsonar.nodejs.executable=$SONAR_NODEJS_EXECUTABLE \
      -X  # Run with debug output
