language: generic

services:
  - docker

before_script:
  # Install Trivy
  - echo "Downloading Trivy..."
  - curl -sfL https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/install.sh | sudo sh -s -- -b /usr/local/bin

script:
  # Build Docker image
  - echo "Building Docker image..."
  - docker build -t trivy-travis:latest .

  # Run Trivy scan on Docker image and generate a JSON report
  - echo "Running Trivy scan on Docker image..."
  - trivy image --timeout 30m --format json -o $(pwd)/trivy-report.json trivy-travis:latest
  
  # Ensure that the report was generated successfully
  - if [ ! -f trivy-report.json ]; then echo "Trivy report not found!"; exit 1; fi

after_script:
  - echo "Uploading report to DefectDojo..."
  - |
    curl -X POST "${DEFECTDOJO_URL}" \
      -H 'accept: application/json' \
      -H "Authorization: ${DEFECTDOJO_API_TOKEN}" \
      -H 'Content-Type: multipart/form-data' \
      -F "test=33" \
      -F "file=@$(pwd)/trivy-report.json;type=application/json" \
      -F "scan_type=Trivy Scan" \
      -F "tags=sample" \
      --max-time 300
