language: generic

services:
  - docker

before_script:
  # Install Trivy
  - wget https://github.com/aquasecurity/trivy/releases/latest/download/trivy_0.56.2_Linux-64bit.deb
  - sudo dpkg -i trivy_0.56.2_Linux-64bit.deb

script:
  # Build Docker imagelanguage: generic

services:
  - docker

before_script:
  # Install Trivy
  - echo "Downloading Trivy..."
  - curl -sfL https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/install.sh | sudo sh -s -- -b /usr/local/bin

script:
  # Build Docker image
  - echo "Building Docker image..."
  - docker build -t trivy-travis:latest .

  # Run Trivy scan on Docker image and generate a JSON report
  - echo "Running Trivy scan on Docker image..."
  - trivy image --severity HIGH,CRITICAL --format json -o trivy-report.json trivy-travis:latest || true
  
  # Ensure that the report was generated successfully
  - if [ ! -f trivy-report.json ]; then echo "Trivy report not found!"; exit 1; fi

after_script:
  # Upload Trivy report to DefectDojo
  - echo "Uploading Trivy report to DefectDojo..."
  - |
    curl -X POST "$DEFECTDOJO_URL" \
      -H "Authorization: Token $DEFECTDOJO_API_TOKEN" \
      -H 'accept: application/json' \
      -H 'Content-Type: multipart/form-data' \
      -F "scan_type=Trivy Scan" \
      -F "file=@trivy-report.json;type=application/json" \
      --max-time 300
  - if [ $? -ne 0 ]; then echo "Failed to upload Trivy report to DefectDojo!"; exit 1; fi

  - echo "Trivy report uploaded successfully to DefectDojo."

  - docker build -t trivy-travis:latest .
  # Scan Docker image with Trivy and save the report in JSON format
  - trivy image --exit-code 1 --severity HIGH,CRITICAL --format json -o $(pwd)/trivy-report.json trivy-travis:latest || true
  # Confirm if trivy-report.json was generated
  - ls -la $(pwd)/trivy-report.json  # Check if trivy-report.json exists and display its details

after_script:
  - echo "Uploading report to DefectDojo..."
  - |
    curl -X POST "${DEFECTDOJO_URL}" \
      -H 'accept: application/json' \
      -H "Authorization: ${DEFECTDOJO_API_TOKEN}" \
      -H 'Content-Type: multipart/form-data' \
      -F "test=33" \
      -F "file=@$(pwd)/trivy-report.json;type=application/json" \
      -F "scan_type=Trivy Scan" \
      -F "tags=sample" \
      --max-time 300
