language: java

jdk:
  - semeru17  # Use JDK 17 (Semeru version)

node_js:
  - "22"  # Ensure Node.js version 22 is installed

before_install:
  - node -v  # Verify Node.js version
  - echo "Node.js version is: $(node -v)"  # Print Node.js version to the log for verification

env:
  - SONAR_NODEJS_EXECUTABLE=$(which node)  # Set the Node.js executable path for SonarQube

install:
  - npm install  # Install dependencies

script:
  - npm test  # Run your tests

after_success:
  - |
    sonar-scanner \
      -Dsonar.projectKey=travis-sonarqube \
      -Dsonar.sources=. \
      -Dsonar.host.url=https://sonar.eha.ng/ \
      -Dsonar.login=$TRAVIS_SONARQUBE \
      -Dsonar.nodejs.executable=$SONAR_NODEJS_EXECUTABLE  # Use the SONAR_NODEJS_EXECUTABLE environment variable
      -X  # Run with debug output
